# Generated by Django 4.0.6 on 2022-07-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maceteros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=300)),
                ('Tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=300)),
                ('Tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tierra_de_Hojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=300)),
                ('Abono', models.CharField(max_length=10)),
            ],
        ),
    ]
