# Generated by Django 4.0.6 on 2022-07-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maceteros',
            new_name='Macetero',
        ),
        migrations.RenameModel(
            old_name='Tierra_de_Hojas',
            new_name='Tierra_de_Hoja',
        ),
    ]
