# Generated by Django 4.0.4 on 2022-07-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_maceteros_macetero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='macetero',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='macetero',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Macetero'),
        ),
    ]
